name: CI-CD Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Run tests or linting here"

  build_and_push_ecr:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        run: |
          IMAGE_URI="${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest"
          echo "Building Docker image..."
          docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} .
          echo "Tagging Docker image..."
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest $IMAGE_URI
          echo "Pushing Docker image to ECR..."
          docker push $IMAGE_URI

  deploy_to_ec2:
    needs: build_and_push_ecr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Docker container to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_INSTANCE_IP }} \
          "docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest && \
           docker stop studentperformance || true && \
           docker rm studentperformance || true && \
           docker run -d --name studentperformance -p 8080:8080 ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest"
